// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyjncaithmssasrdpjtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5am5jYWl0aG1zc2FzcmRwanRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDA5MDQsImV4cCI6MjA2MjAxNjkwNH0.UBYxRiF04XqccUPrCBX_vcEuxdvNraYmOS-YbYm7GWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);